package br.com.send.util;

import org.springframework.beans.factory.annotation.Value;
import org.springframework.stereotype.Service;

@Service
public class TemplateUtil {

	@Value("${url.front}")
	private String URL;
	
	private String getStyle() {
		
		StringBuffer style = new StringBuffer("<style>");
		
		style.append(" img {");
		style.append("    border: none;");
		style.append("    -ms-interpolation-mode: bicubic;");
		style.append("    max-width: 100%;"); 
		style.append("   }");
		style.append("  body {");
		style.append("     background-color: #f6f6f6;");
		style.append("     font-family: sans-serif;");
		style.append("      -webkit-font-smoothing: antialiased;");
		style.append("    font-size: 14px;");
		style.append("    line-height: 1.4;");
		style.append("    margin: 0;");
		style.append("     padding: 0;");
		style.append("     -ms-text-size-adjust: 100%;");
		style.append("     -webkit-text-size-adjust: 100%;"); 
		style.append("  }");
		style.append("  table {");
		style.append("    border-collapse: separate;");
		style.append("    mso-table-lspace: 0pt;");
		style.append("     mso-table-rspace: 0pt;");
		style.append("    width: 100%; }");
		style.append("    table td {");
		style.append("     font-family: sans-serif;");
		style.append("      font-size: 14px;");
		style.append("    vertical-align: top;"); 
		style.append(" }");
		style.append("  .body {");
		style.append("	        background-color: #f6f6f6;");
		style.append("    width: 100%;"); 
		style.append("  }");
		style.append("  .container {");
		style.append("   display: block;");
		style.append("    margin: 0 auto !important;");
		style.append("   max-width: 580px;");
		style.append("    padding: 10px;");
		style.append("    width: 580px;"); 
		style.append(" }");
		style.append("  .content {");
		style.append("    box-sizing: border-box;");
		style.append("    display: block;");
		style.append("    margin: 0 auto;");
		style.append("    max-width: 580px;");
		style.append("    padding: 10px; ");
		style.append("  }");
		style.append("  .main {");
		style.append("    background: #ffffff;");
		style.append("   border-radius: 3px;");
		style.append("   width: 100%;"); 
		style.append("  }");
		style.append("  .wrapper {");
		style.append("   box-sizing: border-box;");
		style.append("    padding: 20px;"); 
		style.append("  }");
		style.append("  .content-block {");
		style.append("    padding-bottom: 10px;");
		style.append("    padding-top: 10px;");
		style.append("  }");
		style.append(" .footer {");
		style.append("    clear: both;");
		style.append("   margin-top: 10px;");
		style.append("   text-align: center;");
		style.append("   width: 100%;"); 
		style.append(" }");
		style.append("  .footer td,");
		style.append(" .footer p,");
		style.append("    .footer span,");
		style.append("    .footer a {");
		style.append("      color: #999999;");
		style.append("       font-size: 12px;");
		style.append("      text-align: center;"); 
		style.append("   }");
		style.append("   h1, h2, h3,");
		style.append("   h4 {");
		style.append("    color: #000000;");
		style.append("    font-family: sans-serif;");
		style.append("    font-weight: 400;");
		style.append("    line-height: 1.4;");
		style.append("    margin: 0;");
		style.append("    margin-bottom: 30px; }");
		style.append("  h1 {");
		style.append("    font-size: 35px;");
		style.append("   font-weight: 300;");
		style.append("   text-align: center;");
		style.append("    text-transform: capitalize;"); 
		style.append("  }");
		style.append("   p,ul,");
		style.append("  ol {");
		style.append("    font-family: sans-serif; ");
		style.append("    font-size: 14px;");
		style.append("     font-weight: normal;");
		style.append("     margin: 0;");
		style.append("    margin-bottom: 15px;"); 
		style.append("  }");
		style.append("    p li,");
		style.append("    ul li,");
		style.append("    ol li {");
		style.append("      list-style-position: inside;");
		style.append("      margin-left: 5px; ");
		style.append("  }");
		style.append("   a { ");
		style.append("    color: #3498db;");
		style.append("     text-decoration: underline;"); 
		style.append("   }");
		style.append("  .btn {");
		style.append("     box-sizing: border-box;");
		style.append("    width: 100%; }");
		style.append("     .btn > tbody > tr > td {");
		style.append("      padding-bottom: 15px; }");
		style.append("    .btn table {");
		style.append("     width: auto;"); 
		style.append("  }");
		style.append("  .btn table td {");
		style.append("      background-color: #ffffff;");
		style.append("      border-radius: 5px;");
		style.append("      text-align: center;"); 
		style.append(" }");
		style.append("     .btn a {");
		style.append("      background-color: #ffffff;");
		style.append("       border: solid 1px #3498db;");
		style.append("      border-radius: 5px;");
		style.append("      box-sizing: border-box;");
		style.append("      color: #3498db;");
		style.append("      cursor: pointer;");
		style.append("      display: inline-block;");
		style.append("     font-size: 14px;");
		style.append("     font-weight: bold;");
		style.append("     margin: 0;");
		style.append("    padding: 12px 25px;");
		style.append("    text-decoration: none;");
		style.append("     text-transform: capitalize;"); 
		style.append("   }");
		style.append("   .btn-primary table td {");
		style.append("     background-color: #3498db;"); 
		style.append("   }");
		style.append("   .btn-primary a {");
		style.append("     background-color: #3498db;");
		style.append("     border-color: #3498db;");
		style.append("    color: #ffffff;"); 
	    style.append("  }");
	    style.append("   .last {");
	    style.append("    margin-bottom: 0;"); 
	    style.append("  }");
	    style.append("  .first {");
	    style.append("    margin-top: 0;"); 
	    style.append("  }");
	    style.append("  .align-center {");
	    style.append("    text-align: center;"); 
	    style.append("   }");
	    style.append("  .align-right {");
	    style.append("    text-align: right;"); 
	    style.append("  }");
	    style.append("  .align-left {");
	    style.append("   text-align: left;"); 
	    style.append(" }");
	    style.append("  .clear {");
	    style.append("   clear: both;"); 
	    style.append(" }");
	    style.append(" .mt0 {");
	    style.append("    margin-top: 0;"); 
	    style.append("  }");
	    style.append("  .mb0 {");
	    style.append("    margin-bottom: 0;"); 
	    style.append("  }");
	    style.append("  .preheader {");
	    style.append("   color: transparent;");
	    style.append("    display: none;");
	    style.append("   height: 0;");
	    style.append("   max-height: 0;");
	    style.append("   max-width: 0;");
	    style.append("   opacity: 0;");
	    style.append("   overflow: hidden;");
	    style.append("  mso-hide: all;");
	    style.append("   visibility: hidden;");
	    style.append("   width: 0;"); 
	    style.append("  }");
	    style.append("  .powered-by a {");
	    style.append("    text-decoration: none;"); 
	    style.append("  }");
	    style.append("  hr {");
	    style.append("   border: 0;");
	    style.append("   border-bottom: 1px solid #f6f6f6;");
	    style.append("   margin: 20px 0;");
	    style.append("  }");
	    style.append("  @media only screen and (max-width: 620px) {");
	    style.append("    table[class=body] h1 {");
	    style.append("      font-size: 28px !important;");
	    style.append("      margin-bottom: 10px !important;"); 
	    style.append("     }");
	    style.append("    table[class=body] p,");
	    style.append("    table[class=body] ul,");
	    style.append("    table[class=body] ol,");
	    style.append("     table[class=body] td,");
	    style.append("     table[class=body] span,");
	    style.append("    table[class=body] a {");
	    style.append("     font-size: 16px !important;"); 
	    style.append("   }");
	    style.append("    table[class=body] .wrapper,");
	    style.append("    table[class=body] .article {");
	    style.append("       padding: 10px !important;"); 
	    style.append("    }");
	    style.append("    table[class=body] .content {");
	    style.append("      padding: 0 !important;"); 
	    style.append("    }");
	    style.append("    table[class=body] .container {");
	    style.append("      padding: 0 !important;");
	    style.append("     width: 100% !important;"); 
	    style.append("   }");
	    style.append("    table[class=body] .main {");
	    style.append("      border-left-width: 0 !important;");
	    style.append("      border-radius: 0 !important;");
	    style.append("      border-right-width: 0 !important;"); 
	    style.append("    }");
	    style.append("    table[class=body] .btn table {");
	    style.append("      width: 100% !important;"); 
	    style.append("    }");
	    style.append("    table[class=body] .btn a {");
	    style.append("      width: 100% !important;"); 
	    style.append("    }");
	    style.append("    table[class=body] .img-responsive {");
	    style.append("      height: auto !important;");
	    style.append("      max-width: 100% !important;        .ExternalClass {");
	    style.append("     width: 100%;"); 
	    style.append("    }");
	    style.append("    .ExternalClass,");
	    style.append("    .ExternalClass p,");
	    style.append("    .ExternalClass span,");
	    style.append("    .ExternalClass font,");
	    style.append("   .ExternalClass td,");
	    style.append("    .ExternalClass div {");
	    style.append("      line-height: 100%;"); 
	    style.append("    }");
	    style.append("   .apple-link a {");
	    style.append("      color: inherit !important;");
	    style.append("      font-family: inherit !important;");
	    style.append("      font-size: inherit !important;");
	    style.append("      font-weight: inherit !important;");
	    style.append("      line-height: inherit !important;");
	    style.append("      text-decoration: none !important;"); 
	    style.append("   }");
	    style.append("    #MessageViewBody a {");
	    style.append("      color: inherit;");
	    style.append("      text-decoration: none;");
	    style.append("     font-size: inherit;");
	    style.append("     font-family: inherit;");
	    style.append("    font-weight: inherit;");
	    style.append("    line-height: inherit;");
	    style.append("    }");
	    style.append("    .btn-primary table td:hover {");
	    style.append("      background-color: #34495e !important;"); 
	    style.append("    }");
	    style.append("    .btn-primary a:hover {");
	    style.append("      background-color: #34495e !important;");
	    style.append("      border-color: #34495e !important;"); 
	    style.append("   }"); 
	    style.append("  }");
	    style.append("</style>");
	    
	    return style.toString();
	}
	      
	public  String getResetSenha(String nome, String chaveTrocaSenha) {
		
		String nomePagina = "alteracaoSenha/"+chaveTrocaSenha;
		
		StringBuffer conteudo = new StringBuffer("<html>");
	
		conteudo.append("<head>");
		conteudo.append("<meta name=\"viewport\" content=\"width=device-width\" />");
		conteudo.append("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />");
		conteudo.append("<title>Send</title>");
		
		conteudo.append(getStyle());
		
		conteudo.append("</head>");
		conteudo.append("<body class=''");
		conteudo.append("<table role='presentation' border='0' cellpadding='0' cellspacing='0' class='body'>"); 
		conteudo.append("<tr>"); 
		conteudo.append("<td>&nbsp;</td>"); 
		conteudo.append("<td class='container'>"); 
		conteudo.append("<div class='content'>"); 
		conteudo.append("<table role='presentation' class='main'>");
		conteudo.append("<tr>");
		conteudo.append("<td class='wrapper'>");
		conteudo.append("<table role='presentation' border='0' cellpadding='0' cellspacing='0'>");
		conteudo.append("<tr>");
		conteudo.append("<td>");
		conteudo.append("<p>Olá, "+nome+"</p>");
		conteudo.append("<p>Parece que esqueceu sua senha, não tem problema, clique abaixo para redefinir sua senha</p>");
	    conteudo.append("<table role='presentation' border='0' cellpadding='0' cellspacing='0' class='btn btn-primary'>");
		conteudo.append("<tbody>");
		conteudo.append("<tr>");
		conteudo.append("<td align='left'>");
		conteudo.append("<table role='presentation' border='0' cellpadding='0' cellspacing='0'>");
		conteudo.append("<tbody>");
		conteudo.append("<tr>");
		conteudo.append("<td> <a href='"+URL+nomePagina+"'>Redefinir Minha Senha</a> </td>");
		conteudo.append("</tr>");
		conteudo.append("</tbody>");
		conteudo.append("</table>");
		conteudo.append("</td>");
		conteudo.append("</tr>");
		conteudo.append("</tbody>");
		conteudo.append("</table>");
		conteudo.append("<p>Caso não consiga abrir, copie e cole o endereço no nagevador "+URL+nomePagina+"</p>");
		conteudo.append("<p>Se você não solicitou uma nova senha, pode ignorar com segurança este e-mail.</p>");
		conteudo.append("</td>");
		conteudo.append("</tr>");
		conteudo.append("</table>");
		conteudo.append("</td>");
		conteudo.append("</tr>");
		conteudo.append("</table>");
		conteudo.append("<div class='footer'>");
		conteudo.append("<table role='presentation' border='0' cellpadding='0' cellspacing='0'>");
		conteudo.append("<tr>");
		conteudo.append("<td class='content-block'>");
		conteudo.append("<span class='apple-link'>Rastreamento de dispositivos. Por favor, não responder o email</span>");
		conteudo.append("<br><a href='http://www.sendsolutions.me'>Send</a>.");
		conteudo.append("</td>");
		conteudo.append("</tr>");
		conteudo.append("<tr>");
		conteudo.append("</td>");
		conteudo.append("</tr>");
		conteudo.append("</table>");
		conteudo.append("</div>");
		conteudo.append("</div>");
		conteudo.append("</td>");
		conteudo.append("<td>&nbsp;</td>");
		conteudo.append("</tr>");
		conteudo.append("</table>");
		conteudo.append("</body>");
		conteudo.append("</html>");
		
		return conteudo.toString();
	}
}
